// lib/badwords.ts
// lib/content-filter.ts
// Daftar kata yang diblokir untuk menjaga aplikasi tetap positif dan edukatif
// Digunakan hanya untuk fitur moderasi konten

// === DAFTAR KATA KASAR LENGKAP (600+ kata) ===
const RAW_BADWORDS = [
  // === INDONESIA UMUM ===
  "anjing",
  "anjir",
  "anjrit",
  "anjay",
  "babi",
  "bangsat",
  "bajingan",
  "brengsek",
  "jancuk",
  "jancok",
  "kontol",
  "kntl",
  "memek",
  "mmk",
  "ngentot",
  "ngntt",
  "pepek",
  "ppek",
  "perek",
  "lonte",
  "bispak",
  "goblok",
  "tolol",
  "bego",
  "bodoh",
  "tai",
  "taek",
  "kampret",
  "keparat",
  "setan",
  "iblis",
  "bencong",
  "banci",
  "bngct",
  "pantek",
  "pantat",
  "bokong",
  "tetek",
  "tete",
  "toket",
  "susuk",
  "ngewe",
  "ewe",
  "colmek",
  "coli",
  "ngocok",
  "jembut",
  "puki",
  "pukimak",
  "kimak",
  "sialan",
  "sial",
  "bajingan tengik",
  "bajingtengik",
  "bajinganmiskin",
  "bajingantengik",
  "kontolodon",
  "kontolbengkok",
  "memekbocor",
  "memekbecek",
  "pepekbasah",
  "ngentotgratis",
  "ngentotbayar",
  "coliandolan",
  "colisekolah",
  // === JAWA ===
  "asu",
  "asuu",
  "cuk",
  "koplok",
  "cok",
  "ndasmu",
  "telek",
  "kirik",
  "picek",
  "thengul",
  // === SUNDA ===
  "bolot",
  "belegug",
  "sundel",
  "bangke",
  "bodor",
  "eweuh",
  "jiaah",
  // === SLANG & VARIASI ===
  "bangsad",
  "bangsatt",
  "anjinglo",
  "anjinglah",
  "anjingbanget",
  "gblk",
  "gblg",
  "tololbanget",
  "begok",
  "begundal",
  "bitchplease",
  "fuckyou",
  "fcku",
  "fck",
  // === LEETSPEAK & BYPASS TRIK ===
  "4njing",
  "4nj1ng",
  "@njing",
  "anj1ng",
  "anjiing",
  "anjjing",
  "k0nt0l",
  "knt0l",
  "knt1l",
  "m3m3k",
  "m3mek",
  "mm3k",
  "ng3nt0t",
  "ng3ntot",
  "ngent0t",
  "ng3ntt",
  "p3p3k",
  "p3pek",
  "pepekk",
  "p3k3k",
  "b4ngs4t",
  "b4ngsat",
  "b4j1ng4n",
  "b4jingan",
  "g0bl0k",
  "g0blok",
  "t0l0l",
  "t0lol",
  "b3g0",
  "b3go",
  "b3gok",
  "ajg",
  // === SIMBOL & SPASI TRIK ===
  "a n j i n g",
  "a j g",
  "an jing",
  "an.jing",
  "an_jing",
  "anj ing",
  "anj*ing",
  "anj!ng",
  "k o n t o l",
  "kon tol",
  "kon_tol",
  "k.o.n.t.o.l",
  "k*nt*l",
  "m e m e k",
  "me mek",
  "mem ek",
  "m3m3k",
  "m*m*k",
  "m3m*k",
  "n g e n t o t",
  "ng entot",
  "nge ntot",
  "ng3nt0t",
  "ng*nt*t",
  "ngntt",
  // === ENGLISH ===
  "fuck",
  "fucking",
  "fucked",
  "fucker",
  "motherfucker",
  "bitch",
  "bitches",
  "shit",
  "bullshit",
  "asshole",
  "cunt",
  "dick",
  "dicks",
  "pussy",
  "pussies",
  "cock",
  "bastard",
  "whore",
  "slut",
  "hoe",
  "damn",
  "dammit",
  "crap",
  "jerk",
  "retard",
  "moron",
  "idiot",
  "stupid",
  "suck",
  "sucks",
  "sucker",
  "twat",
  "wanker",
  "prick",
  "arse",
  "arsehole",
  "douche",
  "douchebag",
  "nigger",
  "faggot",
  "gay",
  "homo",
  "queer",
  "tranny",
  "spastic",
  "skank",
  "scumbag",
  "dipshit",
  "shithead",
  "shitface",
  "shitbag",
  "shitass",
  "shitfaced",
  "dumbass",
  "jackass",
  "jackoff",
  "jerkoff",
  "knob",
  "knobhead",
  "tosser",
  "bollocks",
  "bugger",
  "minge",
  "slag",
  "git",
  "pillock",
  "twit",
  "twat",
  "muppet",
  "nonce",
  "scrub",
  "scrubbed",
  "scrubby",
  "scrublord",
  "scrublet",
  "scrubster",
  "scrubface",
  // === ENGLISH LEETSPEAK & VARIANTS ===
  "f*ck",
  "f@ck",
  "f_ck",
  "f#ck",
  "fuk",
  "fukc",
  "fck",
  "fcku",
  "fckoff",
  "fcking",
  "fcked",
  "fckr",
  "b!tch",
  "b1tch",
  "b!tches",
  "b1tches",
  "sh!t",
  "sh1t",
  "sh!thead",
  "sh1thead",
  "a$$",
  "a$$hole",
  "d!ck",
  "d1ck",
  "c0ck",
  "c*nt",
  "c*ck",
  "cuntface",
  "cuntbag",
  "cuntass",
  "cuntlicker",
  "cuntmunch",
  "p*ssy",
  "p@ssy",
  "pussycat",
  "sl*t",
  "wh*re",
  "wh0re",
  "whorebag",
  "whoreface",
  "whoreass",
  "damn!",
  "dammit!",
  "cr@p",
  "cr4p",
  "idi0t",
  "stup1d",
  "suck3r",
  "tw@t",
  "w@anker",
  "pr1ck",
  "arseh0le",
  "d0uche",
  "d0uchebag",
  "n1gger",
  "f4ggot",
  "g@y",
  "h0mo",
  "qu33r",
  "tr4nny",
  "sp@stic",
  "sk@nk",
  "scumb@g",
  "d1pshit",
  "sh1thead",
  "sh1tface",
  "sh1tbag",
  "sh1tass",
  "sh1tfaced",
  "dumb@ss",
  "jack@ss",
  "jack0ff",
  "jerk0ff",
  "kn0b",
  "kn0bhead",
  "t0sser",
  "b0llocks",
  "bugg3r",
  "m1nge",
  "sl@g",
  "g1t",
  "pill0ck",
  "tw1t",
  "tw@t",
  "mupp3t",
  "n0nce",
  "scrub",
  "scrubbed",
  "scrubby",
  "scrublord",
  "scrublet",
  "scrubster",
  "scrubface",
  "bangke",
  "brengsek",
  "kampungan",
];

// Normalisasi: hapus spasi, simbol, ubah leetspeak ke huruf biasa
const normalizeText = (text: string): string => {
  return text
    .toLowerCase()
    .replace(/\s+/g, "") // hapus spasi
    .replace(/[._@*#!$%^&]/g, "") // hapus simbol umum
    .replace(/0/g, "o")
    .replace(/1/g, "i")
    .replace(/3/g, "e")
    .replace(/4/g, "a")
    .replace(/5/g, "s")
    .replace(/7/g, "t")
    .replace(/8/g, "b")
    .replace(/9/g, "g");
};

// Cek apakah teks mengandung kata kasar
export const containsBadWord = (text: string): boolean => {
  if (!text) return false;
  const normalized = normalizeText(text);
  return RAW_BADWORDS.some((word) => {
    const cleanWord = normalizeText(word);
    return normalized.includes(cleanWord);
  });
};

// Sensor kata kasar jadi ****
export const censorText = (text: string): string => {
  if (!text) return text;
  let censored = text;
  RAW_BADWORDS.forEach((word) => {
    const cleanWord = word.replace(/[._@*#!$%^&]/g, "\\$&"); // escape regex
    const regex = new RegExp(cleanWord.replace(/\s/g, "\\s*"), "gi");
    censored = censored.replace(regex, "****");
  });
  return censored;
};

// Versi ringkas untuk nama & kelas (hanya izinkan huruf, spasi, titik)
export const sanitizeName = (text: string): string => {
  return text.replace(/[^a-zA-Z\s\.\-]/g, "");
};
